version: '3.8'
services:
  app:
    build: ./app
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
